# Generated by Django 5.2.17 on 2026-08-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysDictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_sort', models.IntegerField(db_comment='排序')),
                ('dict_label', models.CharField(db_comment='标签', max_length=100)),
                ('dict_value', models.CharField(db_comment='值', max_length=100)),
                ('dict_type', models.CharField(db_comment='类型（关联 sys_dict_type）', max_length=100)),
                ('css_class', models.CharField(blank=True, db_comment='样式 class', max_length=100, null=True)),
                ('list_class', models.CharField(blank=True, db_comment='列表样式', max_length=100, null=True)),
                ('is_default', models.CharField(db_comment='是否默认：Y/N', max_length=1)),
                ('status', models.CharField(db_comment='状态：0正常 1停用', max_length=1)),
                ('remark', models.CharField(blank=True, db_comment='备注', max_length=500, null=True)),
                ('create_by', models.BigIntegerField(blank=True, db_comment='创建人', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('update_by', models.BigIntegerField(blank=True, db_comment='更新人', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('del_flag', models.CharField(db_comment='逻辑删除', max_length=1)),
            ],
            options={
                'db_table': 'sys_dict_data',
                'db_table_comment': '字典数据表',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SysDictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_name', models.CharField(db_comment='字典名称', max_length=100)),
                ('dict_type', models.CharField(db_comment='字典类型（唯一）', max_length=100, unique=True)),
                ('status', models.CharField(db_comment='状态：0正常 1停用', default='0', max_length=1)),
                ('remark', models.CharField(blank=True, db_comment='备注', max_length=500, null=True)),
                ('create_by', models.BigIntegerField(blank=True, db_comment='创建人', null=True)),
                ('create_time', models.DateTimeField(blank=True, db_comment='创建时间', null=True)),
                ('update_by', models.BigIntegerField(blank=True, db_comment='更新人', null=True)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
                ('del_flag', models.CharField(db_comment='逻辑删除', max_length=1)),
            ],
            options={
                'db_table': 'sys_dict_type',
                'db_table_comment': '字典类型表',
                'managed': True,
            },
        ),
    ]
