# Generated by Django 5.2.17 on 2026-09-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_campusannouncement_target_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(db_comment='编码前缀（业务类型：S/T/CLS/CRS/DEPT）', max_length=10)),
                ('year', models.IntegerField(db_comment='年份（与 prefix 共同构成序列，如 2026）')),
                ('last_value', models.IntegerField(db_comment='已分配的最大序号', default=0)),
                ('seq_width', models.IntegerField(db_comment='序号补零宽度', default=4)),
                ('update_time', models.DateTimeField(blank=True, db_comment='更新时间', null=True)),
            ],
            options={
                'db_table': 'sys_code_sequence',
                'db_table_comment': '业务编码序列表（P1-12）',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('prefix', 'year'), name='uk_code_seq_prefix_year')],
            },
        ),
    ]
