# Generated by Django 5.2.17 on 2026-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_del_flag_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusannouncement',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusclass',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campuscourse',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campuscourseoffering',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campuscourseschedule',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusdepartment',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除：0正常 2删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusfile',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusidempotencykey',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusknowledge',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusleave',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusmessage',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusragchunk',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusraglog',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusragtask',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusscore',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusscoreaudit',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusstudent',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusteacher',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusterm',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='sysdictdata',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='sysdicttype',
            name='del_flag',
            field=models.CharField(db_comment='逻辑删除', db_default='0', default='0', max_length=1),
        ),
    ]
