# Generated by Django 5.2.17 on 2026-09-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_del_flag_db_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campusannouncement',
            name='is_top',
            field=models.CharField(db_comment='是否置顶', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusannouncement',
            name='status',
            field=models.CharField(db_comment='0草稿 1发布 2下架', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campuscourse',
            name='credit',
            field=models.DecimalField(db_comment='学分', db_default=0.0, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='campuscourse',
            name='hours',
            field=models.IntegerField(db_comment='总学时', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusfile',
            name='file_size',
            field=models.BigIntegerField(db_comment='大小（字节）', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusfile',
            name='visibility',
            field=models.CharField(db_comment='可见性（P1-16：1私有 2本人+授权 3登录可见 4公开）', db_default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusidempotencykey',
            name='response_code',
            field=models.IntegerField(db_comment='首次响应 code', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusknowledge',
            name='status',
            field=models.CharField(db_comment='0草稿 1发布（发布即触发向量化）', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusleave',
            name='leave_duration_minutes',
            field=models.IntegerField(db_comment='时长权威字段（P1-14，分钟）', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusleave',
            name='status',
            field=models.CharField(db_comment='0待审批 1通过 2驳回 3撤销', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusleave',
            name='total_days',
            field=models.DecimalField(db_comment='时长（天，由分钟换算，展示用）', db_default=0.0, decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='campusleave',
            name='version',
            field=models.IntegerField(db_comment='乐观锁版本号（3.6/A-02）', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusmessage',
            name='is_read',
            field=models.CharField(db_comment='0未读 1已读', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusragchunk',
            name='chunk_index',
            field=models.IntegerField(db_comment='分片序号', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusragchunk',
            name='source_version',
            field=models.IntegerField(db_comment='文档版本号（编辑后递增，整源重建判定）', db_default=1),
        ),
        migrations.AlterField(
            model_name='campusragchunk',
            name='status',
            field=models.CharField(db_comment='0待向量化 1已向量化 2失败', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusraglog',
            name='completion_tokens',
            field=models.IntegerField(db_comment='输出 token', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusraglog',
            name='cost_time_ms',
            field=models.IntegerField(db_comment='总耗时', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusraglog',
            name='feedback',
            field=models.CharField(db_comment='0未评 1赞 2踩', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusraglog',
            name='hit_count',
            field=models.IntegerField(db_comment='命中检索片段数', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusraglog',
            name='prompt_tokens',
            field=models.IntegerField(db_comment='输入 token', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusragtask',
            name='retry_count',
            field=models.IntegerField(db_comment='已重试次数（上限 3）', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusragtask',
            name='status',
            field=models.CharField(db_comment='0 PENDING 1 PROCESSING 2 SUCCESS 3 FAILED', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusscore',
            name='is_published',
            field=models.CharField(db_comment='0未发布 1已发布', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='campusscore',
            name='version',
            field=models.IntegerField(db_comment='乐观锁版本号（3.6/A-02）', db_default=0),
        ),
        migrations.AlterField(
            model_name='campusterm',
            name='is_current',
            field=models.CharField(db_comment='是否当前学期：0否 1是（任意时刻仅一个）', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='sysdictdata',
            name='dict_sort',
            field=models.IntegerField(db_comment='排序', db_default=0),
        ),
        migrations.AlterField(
            model_name='sysdictdata',
            name='is_default',
            field=models.CharField(db_comment='是否默认：Y/N', db_default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='sysdictdata',
            name='status',
            field=models.CharField(db_comment='状态：0正常 1停用', db_default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='sysdicttype',
            name='status',
            field=models.CharField(db_comment='状态：0正常 1停用', db_default='0', default='0', max_length=1),
        ),
    ]
