# Generated by Django 5.2.17 on 2026-08-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='登录账号')),
                ('nick_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='性别（0未知 1男 2女）')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号（展示脱敏，B-09/P1-17）')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像（campus_file 签名 URL）')),
                ('status', models.CharField(default='0', max_length=1, verbose_name='账号状态：0正常 1停用')),
                ('student_no', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='学号（展示冗余）')),
                ('teacher_no', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='工号（展示冗余）')),
                ('wechat_openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信 openid')),
                ('role_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='角色标识（student/teacher/counselor/admin）')),
                ('password_version', models.IntegerField(default=0, verbose_name='密码版本号（改密自增）')),
                ('create_by', models.BigIntegerField(blank=True, null=True, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_by', models.BigIntegerField(blank=True, null=True, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('del_flag', models.CharField(default='0', max_length=1, verbose_name='逻辑删除：0正常 2删除')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '系统用户',
                'verbose_name_plural': '系统用户',
                'db_table': 'sys_user',
                'ordering': ['id'],
            },
        ),
    ]
