# Generated by Django 5.2.17 on 2026-09-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='del_flag',
            field=models.CharField(db_default='0', default='0', max_length=1, verbose_name='逻辑删除：0正常 2删除'),
        ),
    ]
