-- ============================================================
-- 01_sys_user.sql  sys_user 初始化说明（T0-4 / 设计 5.2）
-- 依据《智慧校园信息管理系统 设计报告》v2.2 5.2 / 3.4（P1-8）
--
-- 重要（P0-1）：sys_user 由 Django CustomUser 模型权威管理
-- （users.CustomUser, db_table='sys_user'），DDL 以 Django migrations 为准。
-- 本脚本不再包含 CREATE TABLE sys_user——如需初始化，请执行：
--   cd bysj/manage && ../server/venv_wsl/bin/python manage.py migrate
--
-- Django migrate 会创建：sys_user + auth_* + django_* 等系统表。
-- 业务表（campus_*）的建表 DDL 见 02_business_tables.sql（初始化/演示用，
-- 正式环境同样以 Django migrations 为准）。
-- ============================================================
